title: Douglas Couto
description: Undergraduate Mechanical Engineer
site_title: 'Douglas corner'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: abhn
blog_url: https://www.nagekar.com
email: douglasrdcouto@gmail.com
keybase_username: abhn

reddit_username: abhn

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 
